### ISSUE TITLE
Example in line 22 of options.py not working.

### ISSUE THREAD

**Issue by RobBW** [victorlei/smop#100]

**Comment by RobBW** [comment]
I ran the Example  2 days ago and could not find the octave-4.0.2 package as per:
ftp://ftp.gnu.org/ftp/octave/octave-4.0.2.tar.gz

The address has changed and the package address is now:
ftp://ftp.gnu.org/gnu/octave/octave-4.0.2.tar.gz

**Comment by victorlei** [comment]
Rob there are many ways of not working.please be more specific

בתאריך 5 בדצמ׳ 2016 07:30,‏ "RobBW" <notifications@github.com> כתב:

**Comment by victorlei** [comment]
oops my fault

בתאריך 5 בדצמ׳ 2016 07:36,‏ "RobBW" <notifications@github.com> כתב:

**Comment by RobBW** [comment]
Sorry, I meant that the ftp address you provided did not work for me. 
It works if changed to read:
ftp://ftp.gnu.org/gnu/octave/octave-4.0.2.tar.gz

**Comment by RobBW** [comment]
I'm new to this game. Do you close the issue or do I?

**Comment by victorlei** [comment]
It doesnt matter who closes the bugreport. If you dont I will.

בתאריך 5 בדצמ׳ 2016 07:40,‏ "RobBW" <notifications@github.com> כתב:
