### ISSUE TITLE
Bug: Dot product and element-wise product translation inverted

### ISSUE THREAD

**Issue by darhlyk** [victorlei/smop#11]
Matlab operator * is the dot product when multiplying matrices or vectors
and is translated to python operator * which is the element-wise multiplication when
using matrices or vectors; while matlab operator .* which is the element-wise multiplication is translated to .dot()

**Comment by zmoddynamics** [comment]
I'm wondering this myself... the latest version 0.28 translates .* into .dot() and it should be something more like numpy.multiply(self,arr) .. Is there a fix ?

**Comment by victorlei** [comment]
To be fixed today

**Comment by victorlei** [comment]
How about this fix?

**Comment by zmoddynamics** [comment]
That looks right.
