### ISSUE TITLE
Converting a file

### ISSUE THREAD

**Issue by RandomForestGump** [victorlei/smop#119]
I am a windows user, using 2.7 python. I have installed the library correctly, but I am unable to find doc on how to run this, ie. convert a.m to .py, can someone please help?

**Comment by RobBW** [comment]
Attached are some notes I put together couple of years ago.
They may help, I haven’t checked them in a while.
Regards
Rob

RobBWilkinson@gmail.com

**Comment by bramson** [comment]
I've posted (basically) this question on StackExchange, It would be great to have the answer there for ease of searching.
 [https://stackoverflow.com/questions/49918487/how-to-use-smop-to-convert-matlab-into-python-code].  Although I've asked about Python3.6, you can simply mentioned that your notes are for 2.7...they would likely still be very useful.

**Comment by victorlei** [comment]
Ported to python3 and fixed several bugs . New bugs introduced.

**Comment by RandomForestGump** [comment]
Thanks Mate!
