### ISSUE TITLE
coudn't able to install in ubuntu . Error

### ISSUE THREAD

**Issue by sameerCoder** [victorlei/smop#121]
Hi,
    couldn't able to install while installing in ubuntu i am getting this error :-1:-

   File "/tmp/easy_install-IS9wtZ/scipy-1.1.0/setup.py", line 450, in setup_package
   ImportError: No module named numpy.distutils.core

how to solve this issue ?

**Comment by sameerCoder** [comment]
after install numpy manually then i am getting this below error :-1: 
~/Downloads/smop-master/smop$ python main.py solver.m
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import lexer
  File "/home/shakib/Downloads/smop-master/smop/lexer.py", line 6, in <module>
    import ply.lex as lex
ImportError: No module named ply.lex

How to solve this issue ?

**Comment by victorlei** [comment]
I think I fixed it.  Could you try to reproduce it in your environment?

**Comment by victorlei** [comment]
Any luck with reproducing the bug?
