### ISSUE TITLE
preserve comments

### ISSUE THREAD

**Issue by johnyf** [victorlei/smop#16]
Comments annotate code as a docstring and at the few places where the code itself does not suffice for readability. For this reason it would be nice to provide an option for converting `MATLAB` comments to `python` comments. This was mentioned also in #12 and in [this issue](http://chiselapp.com/user/victorlei/repository/smop-dev/info/eb47998bad) on `chiselapp`.

**Comment by dalito** [comment]
@victorlei 
Above some changes to support comments are linked. They are surprisingly not in the current master branch. Is this intended or by mistake?
