### ISSUE TITLE
Future Warning: Possible nested set at... creates tons of "str" output

### ISSUE THREAD

**Issue by asaadsellmann** [victorlei/smop#167]
Hi,
I am confused. Excecuting "run.py myfile.m" in pycharms terminal returns the following error:

```
(base) <...\smop>run.py myfile.m
...\Anaconda3\lib\site-packages\ply\lex.py:760 :FutureWarning: Possible nested set at position 65
   c = re.compile('(?P<%s>%s)' % (fname, _get_regex(f)), self.reflags)
...\Anaconda3\lib\site-packages\ply\lex.py:498 :FutureWarnung: Possible nested set at position 118
   lexre = re.compile(regex,reflags)

str
str
str
str
...
```

the "str" output continues for a while^^

I already updated some packages, but the problem seems to be somewhere else (most probably my head^^)

thanks for any advice in advance!

asaad

**Comment by alexpazolinid** [comment]
Same problem over here, any clue ?

**Comment by asaadsellmann** [comment]
Nope sorry, not yet....I started translating myself as noone had an idea..

**Comment by AAAIbrahim** [comment]
Same here .. anyone found a solution?

**Comment by LOO49** [comment]
Did anyone solve this problem??

**Comment by khalil-nour-216355729** [comment]
I tried everything possible to solve this problem, was there any solution found? If yes please share!

**Comment by asaadsellmann** [comment]
Nope, I did not have the time to continue working on it... Closing this issue for now
