### ISSUE TITLE
Problems with matlab class derivation < handle

### ISSUE THREAD

**Issue by ny2292000** [victorlei/smop#71]
I am new to smop and am not sure if there is a way to overlook this error. I am not using strict option but smop doesn't continue the translation after this error. 

C:\smop-0.26.2\smop>smop myClass.m
myClass.m:1.18:syntax error LT=<<>

classdef MyClass < handle
   properties
      Prop1
   end
   methods
      function obj = MyClass(arg)
         obj.Prop1 = arg;
      end
   end
end

**Comment by victorlei** [comment]
matlab classes are not and will not be supported
