### ISSUE TITLE
Use smop to convert a list of codes in a folder

### ISSUE THREAD

**Issue by rfouyang** [victorlei/smop#74]
Hi Is it possible to convert a list of files in a folder

for example:
folderA/a.m
folderA/folderB/b.m
folderA/c.m

Is there a command to convert a.m, b.m and c.m without state each file name one by one?

Thanks.

**Comment by victorlei** [comment]
The usual shell  globbing works. Try foo*.m  bar/*.m. etc

**Comment by victorlei** [comment]
Collect all the files you need in tar archive, then pass it with -a flag

tar cvf my.tar   my_folder
smop -a my.tar

Take a look at this example

    $ wget ftp://ftp.gnu.org/ftp/octave/octave-4.0.2.tar.gz
    $ smop -a octave-4.0.2.tar.gz -g '*/scripts/*.m'
    $ ls -1 *.py | wc
    $ python -m py_compile *.py
    $ ls -1 *.pyc | wc
    $ wget ftp://ftp.gnu.org/ftp/octave/octave-4.0.2.tar.gz
    $ smop -a octave-4.0.2.tar.gz -g '*/scripts/*.m'
    $ ls -1 *.py | wc
    $ python -m py_compile *.py
    $ ls -1 *.pyc | wc
