### ISSUE TITLE
Run it from within Python

### ISSUE THREAD

**Issue by crackerwizard** [victorlei/smop#84]
Hi,

I want to run it from within Python after installing smop. How do I do that? I have a number of matlab files in different folders that I would like to convert to python from within a python script.

Regards

**Comment by victorlei** [comment]
Hello Crack 

Normally you install smop and then use it from command line or from Makefile.  If you need python-level API, you can do this as follows:  assuming you have matlab file foo.m and you want to do whatever is equivalent to 
> smop -o- foo.m

or (which is the same,  but avoids the installation)

> export PYTHONPATH=.
> python main.py -o- foo.m

First, you set the arguments
>>> import sys
>>> sys.argv.append("foo.m")

If you have many arguments, use
>>> sys.argv += "foo.m bar.m bzz.m".split()

Second, you play with location, installation params etc until the following works
>>> import smop
>>> smop.main.main()

This interface will probably change in the next version of smop

**Comment by crackerwizard** [comment]
Thanks a lot. That was helpful.
