### ISSUE TITLE
'zeros' does not seem to be translating

### ISSUE THREAD

**Issue by RobBW** [victorlei/smop#86]
In the attached SMOP translation the Matlab:     A = zeros(x_dim,y_dim,3);
translates to Python:   A = zeros_(x_dim, y_dim, 3)

Pylint in Atom tells me that  'zeros_' is undefined  and that 'zeros' in core.py is is an unused wildcard import. This suggests something is not quite right in the translation process.
Or am I missing something?
[SMOP output - zeros.pdf](https://github.com/victorlei/smop/files/453054/SMOP.output.-.zeros.pdf)

**Comment by victorlei** [comment]
I think this was fixed a few days ago.  Would you try to download a fresh version?

**Comment by RobBW** [comment]
Downloaded as you suggested.
zeros now translates correctly.
Thank you
