### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by aholtzma** [victorlei/smop#93]
On both Linux and MacOS I see the following error when I try to install smop via pip-2.7.

  Downloading smop-0.29.tar.gz (179kB)
    100% |████████████████████████████████| 184kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    usage:

```
    smop [options][file.m ...file.m][-l file.py...]
             or
    smop [options] library.tar [-l file.py...]
smop: error: unrecognized arguments: --egg-base pip-egg-info
```

**Comment by arpit1997** [comment]
@aholtzma I got the same error and don't know the reason. So i tried to run it portable. Don't install this package just install dependencies. and then you can use the package  with following:
```
$ tar zxvf smop.tar.gz
$ cd smop/smop
$ python main.py solver.m
$ python go.py
```
Also try to use cpython if you want a performance boost for your programs.
Hope this helps :cheese: :smile_cat:

**Comment by victorlei** [comment]
i think i fixed it.  please reopen if still  broken
