### ISSUE TITLE
Matlab 'Parfor' raises a parser error message

### ISSUE THREAD

**Issue by RobBW** [victorlei/smop#96]
When I transpiled some code 
[findOrientation.m.txt](https://github.com/victorlei/smop/files/628555/findOrientation.m.txt)
 containing a 'parfor' command it raised the following error:
SyntaxError: Unexpected "=" (parser) and did not process the file.

smop seems to be treating 'parfor' and the associated 'matlabpool' words as variable names and not as commands.

When I changed the code to a regular 'for' command it transpiled correctly.

Might I suggest that known, but unimplemented Matlab commands like 'parfor' insert a message  _"unimplemented in smop - please send me a solution!"_  and allow the transpilation to proceed instead of issuing an error message and stopping.

**Comment by victorlei** [comment]
getting a bug report for parfor in a way implies that everything else does work :) which is excellent news. Parfor was first reported on may 2014 and was never mentioned since then so i assume its a rarely used feature. But seriously, it is a sign of maturity, so maybe i should bump its version to 1.0.0

**Comment by victorlei** [comment]
Thank you for sending a code sample...  Will try to translate it asap

**Comment by micklexqg** [comment]
@RobBW ,Hi, I came across the same problem,
SyntaxError: Unexpected "=" (parser) and did not process the file.
have you solve it?

**Comment by yaelfregier** [comment]
@micklexqg, @RobBW,  @victorlei, Hi, same here! I was trying to transpile the code of https://github.com/danmcduff/iphys-toolbox/blob/master/CHROM_DEHAAN.m
or 
https://github.com/danmcduff/iphys-toolbox/blob/master/POS_WANG.m
for example, and got the same error messages. Any update? Thanks!

**Comment by RobBW** [comment]
Try the forked version at: https://github.com/PatrickFURI/smop <https://github.com/PatrickFURI/smop>  it seems to have fixed some of these problems.
Regards
Rob

RobBWilkinson@gmail.com

**Comment by yaelfregier** [comment]
Thanks a lot Rob! 

Best regards, Yaël.
